In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/winequality-red.csv")

In [ ]:
df

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
x = df.iloc[:,:11].values

In [ ]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
y = df.iloc[:,11].values

In [ ]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [ ]:
df.corr()

fixed acidity  volatile acidity  ...   alcohol   quality
fixed acidity              1.000000         -0.256131  ... -0.061668  0.124052
volatile acidity          -0.256131          1.000000  ... -0.202288 -0.390558
citric acid                0.671703         -0.552496  ...  0.109903  0.226373
residual sugar             0.114777          0.001918  ...  0.042075  0.013732
chlorides                  0.093705          0.061298  ... -0.221141 -0.128907
free sulfur dioxide       -0.153794         -0.010504  ... -0.069408 -0.050656
total sulfur dioxide      -0.113181          0.076470  ... -0.205654 -0.185100
density                    0.668047          0.022026  ... -0.496180 -0.174919
pH                        -0.682978          0.234937  ...  0.205633 -0.057731
sulphates                  0.183006         -0.260987  ...  0.093595  0.251397
alcohol                   -0.061668         -0.202288  ...  1.000000  0.476166
quality                    0.124052         -0.390558  ...  0.476166  1.000000

[12 rows x 12 columns]

In [ ]:
x.shape

(1599, 11)

In [ ]:
y.shape

(1599,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(x,y, test_size = 0.2)

In [ ]:
train_x.shape

(1279, 11)

In [ ]:
train_y.shape

(1279,)

In [ ]:
test_x

array([[ 8.1  ,  0.38 ,  0.48 , ...,  3.3  ,  1.05 ,  9.4  ],
       [ 6.8  ,  0.775,  0.   , ...,  3.45 ,  0.56 , 10.7  ],
       [ 8.1  ,  0.87 ,  0.   , ...,  3.25 ,  0.5  ,  9.8  ],
       ...,
       [10.   ,  0.38 ,  0.38 , ...,  3.15 ,  0.65 ,  8.5  ],
       [ 8.6  ,  0.37 ,  0.65 , ...,  3.27 ,  0.58 , 11.   ],
       [ 9.2  ,  0.43 ,  0.52 , ...,  3.35 ,  0.61 , 11.3  ]])

In [ ]:
test_y

array([5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 7, 6, 6, 6, 6, 5, 6, 6, 7,
       5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 4, 6, 5, 5, 5, 6, 6,
       6, 6, 6, 5, 5, 6, 5, 8, 5, 6, 7, 5, 7, 5, 6, 5, 6, 5, 5, 5, 6, 7,
       6, 5, 6, 7, 6, 6, 6, 6, 5, 6, 5, 7, 6, 5, 6, 5, 5, 5, 6, 7, 5, 5,
       7, 6, 7, 7, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 4, 6, 6, 7, 5,
       6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 6, 7, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6,
       5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 6, 4, 5, 6, 5,
       6, 6, 5, 6, 7, 5, 5, 7, 5, 8, 7, 6, 5, 5, 5, 5, 6, 4, 6, 6, 5, 3,
       5, 5, 5, 5, 5, 6, 5, 6, 6, 7, 6, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 6,
       5, 4, 5, 7, 6, 6, 4, 6, 7, 5, 5, 6, 5, 7, 6, 6, 5, 7, 6, 7, 4, 8,
       5, 6, 7, 5, 4, 6, 5, 5, 5, 5, 5, 5, 6, 6, 7, 5, 6, 5, 7, 7, 6, 4,
       6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5,
       5, 6, 5, 6, 6, 4, 6, 7, 5, 6, 6, 6, 5, 6, 6, 5, 5, 7, 5, 6, 6, 6,
       5, 6, 5, 6, 5, 7, 5, 6, 6, 7, 7, 6, 7, 6, 7,

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
Lin = LinearRegression()

In [ ]:
Lin.fit(train_x,train_y)

LinearRegression()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
pred_y = Lin.predict(test_x)

In [ ]:
pred_y

array([5.70159683, 5.33136077, 5.03952027, 5.77688956, 5.52344831,
       5.02567803, 5.85184093, 5.25284405, 5.44969177, 5.87664104,
       6.15228953, 6.18831277, 5.61535679, 6.09666738, 6.39977021,
       6.50039109, 5.45073413, 5.84711082, 5.28150642, 6.28849871,
       5.7338303 , 5.71567312, 5.04065438, 5.93666529, 6.08004221,
       5.58291092, 5.7289129 , 5.84938405, 5.30467074, 5.1558266 ,
       5.42411515, 4.82423378, 5.18614429, 5.74486594, 6.38248782,
       5.79321671, 5.64558347, 5.76568832, 6.04540235, 5.10419909,
       5.31728609, 5.41749879, 5.45988441, 5.17510893, 6.45775089,
       5.48567347, 6.38217452, 5.89241167, 5.04145741, 5.34921893,
       5.1108924 , 6.73212537, 5.42193889, 5.04697998, 6.07278969,
       5.34439347, 6.20090573, 5.21294526, 5.1959891 , 5.85182974,
       6.08488166, 5.48125095, 5.08190154, 5.33209431, 5.4454263 ,
       5.73029541, 6.29090032, 5.81268457, 6.12610927, 5.62341678,
       6.24257053, 5.46456666, 6.02823398, 5.47206053, 5.46803

In [ ]:
test_y

array([5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 7, 6, 6, 6, 6, 5, 6, 6, 7,
       5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 4, 6, 5, 5, 5, 6, 6,
       6, 6, 6, 5, 5, 6, 5, 8, 5, 6, 7, 5, 7, 5, 6, 5, 6, 5, 5, 5, 6, 7,
       6, 5, 6, 7, 6, 6, 6, 6, 5, 6, 5, 7, 6, 5, 6, 5, 5, 5, 6, 7, 5, 5,
       7, 6, 7, 7, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 4, 6, 6, 7, 5,
       6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 6, 7, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6,
       5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 6, 4, 5, 6, 5,
       6, 6, 5, 6, 7, 5, 5, 7, 5, 8, 7, 6, 5, 5, 5, 5, 6, 4, 6, 6, 5, 3,
       5, 5, 5, 5, 5, 6, 5, 6, 6, 7, 6, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 6,
       5, 4, 5, 7, 6, 6, 4, 6, 7, 5, 5, 6, 5, 7, 6, 6, 5, 7, 6, 7, 4, 8,
       5, 6, 7, 5, 4, 6, 5, 5, 5, 5, 5, 5, 6, 6, 7, 5, 6, 5, 7, 7, 6, 4,
       6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5,
       5, 6, 5, 6, 6, 4, 6, 7, 5, 6, 6, 6, 5, 6, 6, 5, 5, 7, 5, 6, 6, 6,
       5, 6, 5, 6, 5, 7, 5, 6, 6, 7, 7, 6, 7, 6, 7,

In [ ]:
abs(test_y - pred_y)

array([0.70159683, 0.33136077, 0.03952027, 0.77688956, 0.52344831,
       0.02567803, 0.14815907, 0.74715595, 0.44969177, 0.12335896,
       1.15228953, 0.18831277, 0.38464321, 0.90333262, 0.39977021,
       0.50039109, 0.54926587, 0.15288918, 0.28150642, 0.28849871,
       0.2661697 , 1.28432688, 0.04065438, 0.06333471, 0.08004221,
       0.58291092, 0.2710871 , 0.15061595, 0.30467074, 0.1558266 ,
       0.42411515, 0.17576622, 0.18614429, 0.25513406, 0.38248782,
       0.20678329, 0.64558347, 1.76568832, 0.04540235, 0.10419909,
       0.31728609, 0.41749879, 0.54011559, 0.82489107, 0.45775089,
       0.51432653, 0.38217452, 0.89241167, 0.04145741, 0.65078107,
       0.1108924 , 1.26787463, 0.42193889, 0.95302002, 0.92721031,
       0.34439347, 0.79909427, 0.21294526, 0.8040109 , 0.85182974,
       0.08488166, 0.48125095, 0.08190154, 0.33209431, 0.5545737 ,
       1.26970459, 0.29090032, 0.81268457, 0.12610927, 1.37658322,
       0.24257053, 0.53543334, 0.02823398, 0.52793947, 0.46803

In [ ]:
abs(test_y - pred_y).mean()

0.4740267622773482

In [ ]:
from sklearn.metrics import mean_absolute_error

In [ ]:
mean_absolute_error(test_y, pred_y)

0.4740267622773482

In [ ]:
Lin.score(train_x, train_y)

0.35261930269377306

In [ ]:
Lin.score(test_x, test_y)

0.3920934623086403

In [ ]:
print("My model is 36.3 percent accurate")

My model is 36.3 percent accurate
